### ISSUE TITLE
Issue owners

### ISSUE THREAD

**Issue by sanderploegsma** [sanderploegsma/issuebot#3]
Currently, the issues are created by the person who owns the Github access token, instead of something else. Don't know if it's even possible, maybe just add something along the lines of 'This issue was created by a bot' to the body.

**Comment by RickWieman** [comment]
I think issues always have to have an owner with an actual account... For example, Docker uses https://github.com/GordonTheTurtle for this :smiley: 

From the GitHub API:

> Any user with pull access to a repository can create an issue.

**Comment by sanderploegsma** [comment]
Thanks! Creating a seperate account for generated issues is of course up to
the end user, will add it to the readme.
